class AppStrings {
  static String appname = "Mediapp",
      bestDocapp = "Best Doctor \n Appointment App",
      welcomeBack = "Welcome Back!",
      weAreExcited = "We are excited to have you back!",
      signupNow =
          "Signup Now And Start Exploring All That Our App Has To Offer.",
      email = "Email",
      emailHint = "Enter your Email...",
      password = "Password",
      passwordHint = "Enter your passwors here...",
      fullname = "Full Name",
      fullnameHint = "Enter your name here",
      confirmPassword = "Confirm Password ",
      forgetPassword = "Forget Password? ",
      login = "Login ",
      category = "Category",
      doctor = "Doctor Login",
      settings = "Settings",
      signup = "SignUp ",
      search = "Search Doctor ",
      welcome = "WelCome ",
      alreadyHaveAccount = "Already Have an Account? ",
      dontHaveAccount = "Don't Have an Account? ",
      body = "Body",
      ear = "Ear",
      lungs = "Lungs",
      heart = "Heart",
      kidney = "Kidney",
      changePassword = "Change Password",
      termsConditions = "Terms & Conditions",
      signout = "Signout",
      liver = "Liver";
}
